export const ERRORS: Record<number, string> = {
  1: 'Unterminated string',
  2: 'Invalid character',
  3: 'Invalid escape',
  4: 'Unclosed comparison',
  5: 'Unclosed binary operation',
  6: 'Unclosed parenthesized node',
  7: 'Empty parenthesized node',
  8: 'Unclosed function declaration',
  9: 'Parameters should be separated with comma',
  10: 'Unclosed function call',
  11: 'Arguments should be separated with comma',
  12: 'Unclosed directive',
  13: 'Expected directive name',
  14: 'Unknown directive',
  15: 'Expected lua code provided in string',
  16: 'Unclosed assignment',
  17: 'Unclosed block statement',
  18: 'Invalid parameter.',
};
